version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: stonks
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: stonksDB
    ports:
      - 5432:5432 #172.20.0.2(Host)
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - stonks_network
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@stonks.cl
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - 5050:80
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    networks:
      - stonks_network
networks:
  stonks_network:
    driver: bridge
